name: dem-stitcher
channels:
 - conda-forge
 - anaconda
 - defaults
dependencies:
 - python<3.10
 - pip
 - affine
 - boto3
 - dateparser
 - Fiona
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - gdal>=3,<3.4
 - geopandas
 - jinja2
 - joblib
 - jupyter
 - matplotlib
 - numpy
 - pytest
 - rasterio
 - setuptools
 - setuptools_scm
 - Shapely
 - tqdm